package com.dhenton9000.hibernatesecurity;
// Generated Jun 17, 2010 4:41:51 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

 

/**
 * Groups generated by hbm2java
 */

public class Groups  implements java.io.Serializable {


     private int id;
     private String groupName;
     private Set applicationGroupses = new HashSet(0);
     private Set groupAssignmentses = new HashSet(0);

    public Groups() {
        super();
    }

	
    public Groups(int id) {
        super();
        this.id = id;
    }
    public Groups(int id, String groupName, Set applicationGroupses, Set groupAssignmentses) {
       super();
       this.id = id;
       this.groupName = groupName;
       this.applicationGroupses = applicationGroupses;
       this.groupAssignmentses = groupAssignmentses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    
    public Set getApplicationGroupses() {
        return this.applicationGroupses;
    }
    
    public void setApplicationGroupses(Set applicationGroupses) {
        this.applicationGroupses = applicationGroupses;
    }
    public Set getGroupAssignmentses() {
        return this.groupAssignmentses;
    }
    
    public void setGroupAssignmentses(Set groupAssignmentses) {
        this.groupAssignmentses = groupAssignmentses;
    }




}


