   drop table SANDBOX.NetworkAsset;

    create table SANDBOX.NetworkAsset (
        DTYPE varchar(31) not null,
        db_id integer generated by default as identity unique,
        assetDescription varchar(255),
        ipAddress varchar(255),
        manufacturerName varchar(255),
        switchIdentifier varchar(255),
        switchType varchar(255),
        employeeName varchar(255),
        memory integer,
        primary key (db_id)
    );
