/*
 * Generated by eclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dhenton9000.classic.controllers.actions;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.DynaActionForm;
import org.apache.struts.actions.DispatchAction;

import com.dhenton9000.classic.dao.ClassicCarsDAO;
import com.dhenton9000.classic.dao.generated.Employee;
import com.dhenton9000.classic.dao.generated.Office;
import com.dhenton9000.classic.dao.generated.Product;
import com.dhenton9000.classic.generic.dao.DataAccessLayerException;

/**
 * eclipse Struts Creation date: 05-19-2011
 */
public class OfficeAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	private static Logger log = LogManager.getLogger(ClassicCarsDAO.class);

	/**
	 * This is called by operation parameter for the products Struts action
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws IOException
	 * @throws ServletException
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws IOException, ServletException {

		DynaActionForm newOfficeForm = (DynaActionForm) form;
		ActionErrors errors = validateForm(newOfficeForm);
		if (errors.isEmpty())
			return mapping.findForward("success");
		else
		{
			request.setAttribute("errors", errors) ;
			return mapping.findForward("fail");
			
		}

	}

	public ActionErrors validateForm(DynaActionForm form) {
		ActionErrors errors = new ActionErrors();
		String phone = form.getString("phone");
		String city = form.getString("city");
		String state = form.getString("state");
		String country = form.getString("country");

		if (phone == null || phone.length() == 0) {
			errors.add("phone", new ActionError("errors.generic.item",
					"phone required"));
		}
		if (city == null || city.length() == 0) {
			errors.add("city", new ActionError("errors.generic.item",
					"city required"));
		}
		if (state == null || state.length() == 0) {
			errors.add("state", new ActionError("errors.generic.item",
					"state required"));
		}
		if (country == null || country.length() == 0) {
			errors.add("country", new ActionError("errors.generic.item",
					"country required"));
		}

		return errors;
	}

}