/*
 * Generated by eclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dhenton9000.classic.controllers.actions;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.dhenton9000.classic.dao.ClassicCarsDAO;
import com.dhenton9000.classic.dao.generated.Employee;
import com.dhenton9000.classic.dao.generated.Office;
import com.dhenton9000.classic.dao.generated.Product;
import com.dhenton9000.classic.generic.dao.DataAccessLayerException;

/**
 * eclipse Struts Creation date: 05-19-2011
 */
public class SimpleDisplayAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	private static Logger log = LogManager.getLogger(ClassicCarsDAO.class);
	
	
	/**
	 * This is called by operation parameter for the products Struts action
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws IOException
	 * @throws ServletException
	 */
	public ActionForward simpleProductDisplay(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {
		log.debug("in action product");
		performDataOperation(request,Product.class);
		
		return mapping.findForward("simple.product.display");

	}

	public ActionForward simpleEmployeeDisplay(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {
		log.debug("in action employee");
		performDataOperation(request,Employee.class);
		
		return mapping.findForward("simple.employee.display");

	}
	public ActionForward simpleOfficeDisplay(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {
		log.debug("in action office");
		performDataOperation(request,Office.class);
		
		return mapping.findForward("simple.office.display");

	}

	private void performDataOperation(HttpServletRequest request, Class classzz) {
		ClassicCarsDAO cDAO = ClassicCarsDAO.getInstance()  ;
		
		List things = null; 
		try {
			things = cDAO.findAll(classzz);
		} catch (DataAccessLayerException e) {
			log.error(e);
			
		}
		log.debug("items found "+things.size());
		
		ArrayList t = new ArrayList();
		int pLimit = 10;
		int limit = things.size();
		if (things.size() > pLimit)
		{
			limit = pLimit;
		}
		 
		for (int j=0;j<limit;j++)
		{
			t.add(things.get(j));
			
		}
		
		request.setAttribute("itemDisplay",t);
	}
}