create table poll_table (
        poll_table_id INT NOT NULL generated by default as identity,
        status VARCHAR(15) CONSTRAINT sizes_ck 
        CHECK (status IN ('PENDING', 'IN PROGRESS', 'COMPLETE', 'ERROR')),
        target_table_id integer,
        primary key( poll_table_id ));