
package com.dhenton9000.cxf.sample;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-09-02T14:18:57.014-05:00
 * Generated source version: 2.4.1
 */

@WebFault(name = "InventoryProcessResponse", targetNamespace = "http://dhenton9000.inventory/schema/InventoryBusSchema")
public class InventoryServiceOperationFault extends Exception {
    
    private com.dhenton9000.cxf.sample.InventoryProcessResponse inventoryProcessResponse;

    public InventoryServiceOperationFault() {
        super();
    }
    
    public InventoryServiceOperationFault(String message) {
        super(message);
    }
    
    public InventoryServiceOperationFault(String message, Throwable cause) {
        super(message, cause);
    }

    public InventoryServiceOperationFault(String message, com.dhenton9000.cxf.sample.InventoryProcessResponse inventoryProcessResponse) {
        super(message);
        this.inventoryProcessResponse = inventoryProcessResponse;
    }

    public InventoryServiceOperationFault(String message, com.dhenton9000.cxf.sample.InventoryProcessResponse inventoryProcessResponse, Throwable cause) {
        super(message, cause);
        this.inventoryProcessResponse = inventoryProcessResponse;
    }

    public com.dhenton9000.cxf.sample.InventoryProcessResponse getFaultInfo() {
        return this.inventoryProcessResponse;
    }
}
