/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/formatter/Formatter.e.vm.java
 */
package com.dhenton9000.springfuse.formatter;

import java.text.ParseException;
import java.util.Locale;

import com.dhenton9000.springfuse.domain.Book;
import com.dhenton9000.springfuse.service.BookService;
import com.dhenton9000.springfuse.formatter.support.DiscoverableFormatter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * {@link Formatter} for {@link Book} that is picked by automatically by {@link CustomFormattingConversionServiceFactory}
 * 
 * @see Formatter
 * @see CustomFormattingConversionServiceFactory
 */
@Component
public class BookFormatter implements DiscoverableFormatter<Book> {

    @Autowired
    private BookService bookService;

    @Override
    public Class<Book> getTarget() {
        return Book.class;
    }

    @Override
    public String print(Book book, Locale locale) {
        if (book == null) {
            return "";
        }

        StringBuilder sb = new StringBuilder();
        // make a nice display string here...

        if (book.getTitle() != null) {
            sb.append(book.getTitle()).append(" ");
        }

        if (sb.length() > 0) {
            return sb.toString();
        } else if (book.isPrimaryKeySet()) {
            return book.getPrimaryKey().toString();
        } else {
            return book.toString();
        }
    }

    @Override
    public Book parse(String text, Locale locale) throws ParseException {
        if (text == null || text.isEmpty()) {
            return new Book();
        }
        Book book = bookService.getByPrimaryKey(new Integer(text));
        return book != null ? book : new Book();
    }
}
