/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/manager/ManagerImpl.e.vm.java
 */
package com.dhenton9000.springfuse.service;

import org.apache.log4j.Logger;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.dhenton9000.springfuse.dao.support.GenericDao;
import com.dhenton9000.springfuse.service.support.GenericEntityServiceImpl;
import com.dhenton9000.springfuse.domain.Legacy;
import com.dhenton9000.springfuse.domain.LegacyPk;
import com.dhenton9000.springfuse.dao.LegacyDao;

/**
 *
 * Default implementation of the {@link LegacyService} interface
 * @see LegacyService
 */
@Service("legacyService")
public class LegacyServiceImpl extends GenericEntityServiceImpl<Legacy, LegacyPk> implements LegacyService {

    @SuppressWarnings("unused")
    private static final Logger logger = Logger.getLogger(LegacyServiceImpl.class);

    protected LegacyDao legacyDao;

    @Autowired
    public void setLegacyDao(LegacyDao legacyDao) {
        this.legacyDao = legacyDao;
    }

    /**
     * Dao getter used by the {@link GenericEntityServiceImpl}.
     */
    @Override
    public GenericDao<Legacy, LegacyPk> getDao() {
        return legacyDao;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Legacy getNew() {
        return new Legacy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Legacy getNewWithDefaults() {
        Legacy result = getNew();
        result.initDefaultValues();
        return result;
    }

}