
    drop table SANDBOX.NetworkAsset;

    drop table SANDBOX.PersonalComputer;

    drop table SANDBOX.Switch;

    create table SANDBOX.NetworkAsset (
        db_id integer generated by default as identity unique,
        assetDescription varchar(255),
        ipAddress varchar(255),
        primary key (db_id)
    );

    create table SANDBOX.PersonalComputer (
        db_id integer not null unique,
        assetDescription varchar(255),
        ipAddress varchar(255),
        employeeName varchar(255),
        memory integer not null,
        primary key (db_id)
    );

    create table SANDBOX.Switch (
        db_id integer not null unique,
        assetDescription varchar(255),
        ipAddress varchar(255),
        manufacturerName varchar(255),
        switchIdentifier varchar(255),
        switchType varchar(255),
        primary key (db_id)
    );
