drop table person_student;
drop table person_professional;
drop table person_address;
drop table person;
drop table person_type;


CREATE TABLE PERSON_TYPE (
    ID integer generated by default as identity,
    NAME varchar(50) not null,
    CREATED timestamp,
    primary key (ID)    
);

CREATE TABLE PERSON (
    ID integer generated by default as identity,
    FIRST_NAME varchar(50) not null,
    LAST_NAME varchar(50) not null,
    TYPE integer, 
    CREATED timestamp,
    primary key (ID),
    CONSTRAINT FK_PERSON_TYPE FOREIGN KEY (TYPE) REFERENCES PERSON_TYPE(ID)
);

CREATE TABLE PERSON_STUDENT (
    ID integer not null,  
    SCHOOL_NAME varchar(50) not null,
    CREATED timestamp,
    CONSTRAINT FK_PERSON_STUDENT_ID FOREIGN KEY (ID) REFERENCES PERSON(ID)  
);

CREATE TABLE PERSON_PROFESSIONAL (
    ID integer not null,  
    COMPANY_NAME varchar(50) not null,
    CREATED timestamp,
    CONSTRAINT FK_PERSON_PROFESSIONAL_ID FOREIGN KEY (ID) REFERENCES PERSON(ID)  
);

CREATE TABLE PERSON_ADDRESS (
    ID integer generated by default as identity,
    PERSON_ID integer,  
    ADDRESS varchar(255),
    CITY varchar(50) not null,
    STATE varchar(50) ,
    ZIP_POSTAL varchar(30) not null,
    COUNTRY varchar(50) not null,
    CREATED timestamp,
    PRIMARY KEY (ID),
    CONSTRAINT FK_ADDRESS_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID) 
);
