package com.dhenton9000.registration.components.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-01-26T15:49:54.422-06:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "uri:dhenton9000:registrationService", name = "RegistrationServiceWSDL")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RegistrationServiceWSDL {

    @WebResult(name = "RegisterResponse", targetNamespace = "uri:dhenton9000:registrationService:ref", partName = "outputParameter")
    @WebMethod(operationName = "Register", action = "uri:dhenton9000:registrationService/Register")
    public RegisterResponse register(
        @WebParam(partName = "inputParameter", name = "RegisterInput", targetNamespace = "uri:dhenton9000:registrationService:ref")
        RegisterInput inputParameter
    );
}
