
    alter table CHOICE 
        drop constraint FK767051A14A977F93;

    drop table CHOICE;

    drop table QUESTION;

    create table CHOICE (
        CHOICE_ID bigint generated by default as identity,
        TEXT varchar(255),
        QUESTION_ID bigint,
        primary key (CHOICE_ID)
    );

    create table QUESTION (
        QUESTION_ID bigint generated by default as identity,
        TEXT varchar(255),
        primary key (QUESTION_ID)
    );

    alter table CHOICE 
        add constraint FK767051A14A977F93 
        foreign key (QUESTION_ID) 
        references QUESTION;
