<%--
 | (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 | Source code generated by Celerio, a Jaxio product
 | Want to use Celerio within your company? email us at info@jaxio.com
 | Follow us on twitter: @springfuse
 | Template pack-mvc-3:src/main/webapp/WEB-INF/views/domain/search.e.vm.jsp
--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"
%><%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"
%><%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"
%><%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"
%><head>
	<title><fmt:message key="contactInfo" />: <fmt:message key="crud.functionalities.example" /></title>
</head>
<body>
	<span class="ui-state-highlight button button-search"><fmt:message key="contactInfo" /></span> 
	<a href="${pageContext.request.contextPath}/domain/contactinfo/create" class="button button-create"><fmt:message key="crud.functionalities.create" /></a> 
	<a href="${pageContext.request.contextPath}/domain/contactinfo/showcase" class="button button-create"><fmt:message key="crud.functionalities.showcase" /></a>

	<form:form action="${pageContext.request.contextPath}/domain/contactinfo/list" modelAttribute="contactInfoSearchForm" class="search">
		<table class="show">
			<tbody>
				<tr>
					<th><fmt:message key="contactInfo_accountId" /></th>
					<td>
						<form:select id="parentRestriction" path="parentNullRestriction.restriction" cssClass="number">
							<form:options />
						</form:select>
						<script>
						$('#parentRestriction').change(function() {
							if ($('#parentRestriction option:selected').val() == 'SPECIFIED') { 
								$('#parentLink').removeAttr('disabled').focus();
							} else { 
								$('#parentLink').attr('disabled', 'disabled'); 
							}
						});
						</script>
						<form:select id="parentLink" path="contactInfo.parent" cssClass="required {maxlength: 32 minlength: 32}">
							<form:option value="" label=""/>
							<form:options items="${parents}" itemValue="primaryKey"/>
						</form:select>
						<form:errors path="contactInfo.parent" cssClass="error"/>
						<form:errors path="contactInfo.accountId" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="contactInfo_civility" /></th>
					<td>
						<form:radiobuttons path="contactInfo.civility" />
						<form:errors path="contactInfo.civility" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="contactInfo_lastName" /></th>
					<td>
						<form:input path="contactInfo.lastName"/>
						<form:errors path="contactInfo.lastName" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="contactInfo_firstName" /></th>
					<td>
						<form:input path="contactInfo.firstName"/>
						<form:errors path="contactInfo.firstName" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="contactInfo_birthDate" /></th>
					<td>
						<label for="birthDateRange.fromDate"><fmt:message key="search.date.from" /></label>
						<form:input path="birthDateRange.fromDate" cssClass="datepicker"/>
						<label for="birthDateRange.toDate"><fmt:message key="search.date.to" /></label>
						<form:input path="birthDateRange.toDate" cssClass="datepicker"/>
						<form:errors path="contactInfo.birthDate" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="contactInfo_otherDate" /></th>
					<td>
						<label for="otherDateRange.fromDate"><fmt:message key="search.date.from" /></label>
						<form:input path="otherDateRange.fromDate" cssClass="datepicker"/>
						<label for="otherDateRange.toDate"><fmt:message key="search.date.to" /></label>
						<form:input path="otherDateRange.toDate" cssClass="datepicker"/>
						<form:errors path="contactInfo.otherDate" cssClass="error"/>
					</td>
				</tr>
			</tbody>
			<tfoot>
				<tr>
					<td colspan="2">
						<input type="submit" class="button button-search" value="<fmt:message key="crud.search.button" />"/>
					</td>
				</tr>
			</tfoot>
		</table>
	</form:form>
	<div id="result"/>
</body>
