<%--
 | (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 | Source code generated by Celerio, a Jaxio product
 | Want to use Celerio within your company? email us at info@jaxio.com
 | Follow us on twitter: @springfuse
 | Template pack-mvc-3:src/main/webapp/WEB-INF/views/domain/update.e.vm.jsp
--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"
%><%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"
%><%@ taglib prefix="spring" uri="http://www.springframework.org/tags"
%><%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"
%><%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"
%><head>
	<title><fmt:message key="contactInfo" />: <fmt:message key="crud.functionalities.update" /></title>
</head>
<body>
	<a href="${pageContext.request.contextPath}/domain/contactinfo/search" class="ajaxy button button-search"><fmt:message key="contactInfo" /></a>
	<a href="${pageContext.request.contextPath}/domain/contactinfo/show/${contactInfo.primaryKey}" class="ajaxy button button-show"><fmt:message key="crud.show.button" /></a>
	<span class="ui-state-highlight button button-edit"><fmt:message key="crud.edit.button" /></span>
	<a href="${pageContext.request.contextPath}/domain/contactinfo/delete/${contactInfo.primaryKey}" class="modal button button-delete"><fmt:message key="crud.delete.button" /></a>

	<form:form action="${pageContext.request.contextPath}/domain/contactinfo/update/${contactInfo.primaryKey}" modelAttribute="contactInfo" method="POST">
		<form:errors cssClass="error"/>
		<form:hidden path="id"/>
		<table class="edit">
			<tbody>
				<tr>
					<th><fmt:message key="contactInfo_accountId" /> <em>*</em></th>
					<td>
						<c:choose>
						<c:when test="${not empty contactInfo.parent}">
							<spring:eval expression="contactInfo.parent" />
						</c:when>
						<c:otherwise>
						<form:select path="parent" cssClass="required {maxlength: 32 minlength: 32}">
							<form:options items="${parents}" itemValue="primaryKey"/>
						</form:select>
 						<form:errors path="parent" cssClass="error"/>
						</c:otherwise>
						</c:choose>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="contactInfo_civility" /></th>
					<td>
						<form:radiobuttons path="civility" cssClass="{maxlength: 2 minlength: 2}" />
						<form:errors path="civility" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="contactInfo_lastName" /></th>
					<td>
						<form:input path="lastName" cssClass="{maxlength: 255}" maxlength="255" size="100"/>
						<form:errors path="lastName" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="contactInfo_firstName" /></th>
					<td>
						<form:input path="firstName" cssClass="{maxlength: 255}" maxlength="255" size="100"/>
						<form:errors path="firstName" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="contactInfo_birthDate" /></th>
					<td>
						<form:input path="birthDate" cssClass="datepicker" size="11"/>
						<form:errors path="birthDate" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="contactInfo_otherDate" /></th>
					<td>
						<form:input path="otherDate" cssClass="datepicker" size="11"/>
						<form:errors path="otherDate" cssClass="error"/>
					</td>
				</tr>
			</tbody>
			<tfoot>
				<tr>
					<td colspan="2">
						<input type="submit" class="button button-save" value="<fmt:message key="crud.save.button" />" />
					</td>
				</tr>
			</tfoot>
		</table>
	</form:form>
</body>
