package com.dhenton9000.admissions.ws.impl;

import com.dhenton9000.admissions.components.ws.AdmitSubject;
import com.dhenton9000.admissions.components.ws.AdmitSubjectResponse;
import com.dhenton9000.admissions.components.ws.ObjectFactory;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-12-12T15:22:32.850-06:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://www.mule-health.com/SOA/service/admission/1.0", name = "Admission")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Admission {

    @WebResult(name = "admitSubjectResponse", targetNamespace = "http://www.mule-health.com/SOA/message/1.0", partName = "parameters")
    @WebMethod(action = "http://http://www.mule-health.com/SOA/service/admission/1.0/admitSubject")
    public AdmitSubjectResponse admitSubject(
        @WebParam(partName = "parameters", name = "admitSubject", targetNamespace = "http://www.mule-health.com/SOA/message/1.0")
        AdmitSubject parameters
    );
}
