
    alter table CHOICE_TWO 
        drop constraint FK3CE90E8E120D947;

    drop table CHOICE_TWO;

    drop table QUESTION_TWO;

    create table CHOICE_TWO (
        CHOICE_ID bigint generated by default as identity,
        TEXT varchar(255),
        QUESTION_ID bigint,
        primary key (CHOICE_ID)
    );

    create table QUESTION_TWO (
        QUESTION_ID bigint generated by default as identity,
        TEXT varchar(255),
        primary key (QUESTION_ID)
    );

    alter table CHOICE_TWO 
        add constraint FK3CE90E8E120D947 
        foreign key (QUESTION_ID) 
        references QUESTION_TWO;
