
    alter table SANDBOX.CLASS_ASSIGNMENTS 
        drop constraint FK3761B2BF70FFB10E;

    alter table SANDBOX.CLASS_ASSIGNMENTS 
        drop constraint FK3761B2BF56A37C79;

    alter table SANDBOX.PersonalComputer 
        drop constraint FKF7E80D9BD409F9CC;

    alter table SANDBOX.Switch 
        drop constraint FK9460A354D409F9CC;

    drop table SANDBOX.CLASSES;

    drop table SANDBOX.CLASS_ASSIGNMENTS;

    drop table SANDBOX.NetworkAsset;

    drop table SANDBOX.PersonalComputer;

    drop table SANDBOX.STUDENTS;

    drop table SANDBOX.Switch;

    create table SANDBOX.CLASSES (
        CLASS_ID bigint generated by default as identity,
        CLASS_NAME varchar(255),
        SEATING_CAPACITY integer,
        primary key (CLASS_ID)
    );

    create table SANDBOX.CLASS_ASSIGNMENTS (
        classId bigint not null,
        studentId bigint not null,
        primary key (studentId, classId)
    );

    create table SANDBOX.NetworkAsset (
        db_id integer generated by default as identity unique,
        assetDescription varchar(255),
        ipAddress varchar(255),
        primary key (db_id)
    );

    create table SANDBOX.PersonalComputer (
        employeeName varchar(255),
        memory integer not null,
        db_id integer not null,
        primary key (db_id)
    );

    create table SANDBOX.STUDENTS (
        STUDENT_ID bigint generated by default as identity,
        EMAIL varchar(255) not null,
        STUDENT_GPA float,
        STUDENT_NAME varchar(255),
        primary key (STUDENT_ID)
    );

    create table SANDBOX.Switch (
        manufacturerName varchar(255),
        switchIdentifier varchar(255),
        switchType varchar(255),
        db_id integer not null,
        primary key (db_id)
    );

    alter table SANDBOX.CLASS_ASSIGNMENTS 
        add constraint FK3761B2BF70FFB10E 
        foreign key (classId) 
        references SANDBOX.CLASSES;

    alter table SANDBOX.CLASS_ASSIGNMENTS 
        add constraint FK3761B2BF56A37C79 
        foreign key (studentId) 
        references SANDBOX.STUDENTS;

    alter table SANDBOX.PersonalComputer 
        add constraint FKF7E80D9BD409F9CC 
        foreign key (db_id) 
        references SANDBOX.NetworkAsset;

    alter table SANDBOX.Switch 
        add constraint FK9460A354D409F9CC 
        foreign key (db_id) 
        references SANDBOX.NetworkAsset;
