package com.dhenton9000.admissions.components.ws.billing;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-12-18T14:41:14.697-06:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://www.mule-health.com/SOA/service/billing/1.0", name = "Billing")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Billing {

    @WebResult(name = "createBillResponse", targetNamespace = "http://www.mule-health.com/SOA/message/1.0", partName = "parameters")
    @WebMethod(action = "http://http://www.mule-health.com/SOA/service/billing/1.0/createBill")
    public CreateBillResponse createBill(
        @WebParam(partName = "parameters", name = "createBill", targetNamespace = "http://www.mule-health.com/SOA/message/1.0")
        CreateBill parameters
    );
}
