/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/hibernate/DAOHibernate.e.vm.java
 */
package com.dhenton9000.springfuse.dao;

import org.hibernate.Criteria;
import org.hibernate.criterion.Conjunction;
import org.hibernate.criterion.Restrictions;
import org.springframework.stereotype.Repository;
import com.dhenton9000.springfuse.dao.BookDao;
import com.dhenton9000.springfuse.dao.hibernate.HibernateUtil;
import com.dhenton9000.springfuse.dao.support.SearchTemplate;

import com.dhenton9000.springfuse.domain.Account;
import com.dhenton9000.springfuse.domain.Book;
import com.dhenton9000.springfuse.dao.hibernate.HibernateGenericDao;

/**
 * Hibernate implementation of the Book DAO interface.
 */
@Repository
public class BookDaoImpl extends HibernateGenericDao<Book, Integer> implements BookDao {
    public BookDaoImpl() {
        super(Book.class);
    }

    /**
     * Constructs the search by example criteria using not only the passed book but also its associated entities. 
     */
    @Override
    public Criteria getCriteria(Book book, SearchTemplate searchTemplate) {
        // Call super to construct the criteria of the 'root' entity.
        Criteria criteria = super.getCriteria(book, searchTemplate);

        // many-to-one: "account"
        // Note 1: If 'accountId' != null, no need to add a criteria as the current criteria 
        // already takes this property into account.
        // Note 2: By convention, if the example for "account" has no property set 
        // and "account" is not null we assume that you want a not null criteria. 
        if (book.getAccountId() == null && book.getAccount() != null) {
            criteria.add(Restrictions.isNotNull("account"));
            criteria.createCriteria("account").add(HibernateUtil.constructExample(book.getAccount(), searchTemplate));
        }

        return criteria;
    }
}