<?xml version="1.0" encoding="UTF-8"?>
<definitions name="inventoryService" targetNamespace="http://shoemall.com/inventoryService/wsdl"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://shoemall.com/inventoryService/wsdl" xmlns:ns="http://shoemall.com/schema/InventoryBusSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="http://shoemall.com/inventoryService/wsdl">
            <xsd:import namespace="http://shoemall.com/schema/InventoryBusSchema" schemaLocation="InventoryProcessExploded.xsd"/>
        </xsd:schema>
    </types>
    <message name="inventoryServiceOperationRequest">
        <part name="inventoryProcessRequest" element="ns:InventoryProcessRequest"/>
    </message>
    <message name="inventoryServiceOperationResponse">
        <part name="inventoryProcessResponse" element="ns:InventoryProcessResponse"/>
    </message>
    <message name="inventoryServiceOperationFault">
        <part name="inventoryProcessFault" element="ns:InventoryProcessResponse"/>
    </message>
    <portType name="inventoryServicePortType">
        <operation name="inventoryServiceOperation">
            <input name="serviceInput" message="tns:inventoryServiceOperationRequest"/>
            <output name="serviceOutput" message="tns:inventoryServiceOperationResponse"/>
            <fault name="serviceFault" message="tns:inventoryServiceOperationFault"/>
        </operation>
    </portType>
    <binding name="inventoryServiceBinding" type="tns:inventoryServicePortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="inventoryServiceOperation">
            <soap:operation/>
            <input name="serviceInput">
                <soap:body use="literal"/>
            </input>
            <output name="serviceOutput">
                <soap:body use="literal"/>
            </output>
            <fault name="serviceFault">
                <soap:fault use="literal" name="serviceFault"/>
            </fault>
        </operation>
    </binding>
    <service name="inventoryServiceService">
        <port name="inventoryServicePort" binding="tns:inventoryServiceBinding">
            <soap:address location="http://localhost:4444/inventoryServiceService/inventoryServicePort"/>
        </port>
    </service>
</definitions>


