/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/web/controller/restController.e.vm.java
 */
package com.dhenton9000.springfuse.web.controller.more;

import static org.springframework.http.HttpStatus.INTERNAL_SERVER_ERROR;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.support.FormattingConversionService;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

import com.dhenton9000.springfuse.web.util.AutoCompleteResult;
import com.dhenton9000.springfuse.web.util.SearchParameters;
import com.dhenton9000.springfuse.domain.more.MoreTypesDemo;
import com.dhenton9000.springfuse.service.more.MoreTypesDemoService;

@Controller
@RequestMapping("domain/rest/moretypesdemo/")
public class MoreTypesDemoRestController {
    @Autowired
    public FormattingConversionService formattingConversionService;

    @Autowired
    private MoreTypesDemoService moreTypesDemoService;

    @RequestMapping(value = "/", method = POST)
    @ResponseBody
    public MoreTypesDemo create(@Valid MoreTypesDemo moreTypesDemo) {
        moreTypesDemoService.save(moreTypesDemo);
        return moreTypesDemo.copy();
    }

    @RequestMapping(value = "/", method = POST, headers = "content-type:application/json")
    @ResponseBody
    public MoreTypesDemo jsonCreate(@Valid @RequestBody MoreTypesDemo moreTypesDemo) {
        moreTypesDemoService.save(moreTypesDemo);
        return moreTypesDemo.copy();
    }

    @RequestMapping(value = "/", method = GET)
    @ResponseBody
    public List<MoreTypesDemo> list(MoreTypesDemo moreTypesDemo, SearchParameters searchParameters) {
        List<MoreTypesDemo> moreTypesDemos = moreTypesDemoService.find(moreTypesDemo, searchParameters
                .toSearchTemplate());
        List<MoreTypesDemo> ret = new ArrayList<MoreTypesDemo>();
        for (MoreTypesDemo _moreTypesDemo : moreTypesDemos) {
            ret.add(_moreTypesDemo.copy());
        }
        return ret;
    }

    @RequestMapping(value = "/{pk}", method = GET)
    @ResponseBody
    public MoreTypesDemo get(@PathVariable("pk") MoreTypesDemo moreTypesDemo) {
        return moreTypesDemo.copy();
    }

    @RequestMapping(value = "/{pk}", method = PUT)
    @ResponseBody
    public MoreTypesDemo update(@PathVariable("pk") MoreTypesDemo moreTypesDemoToUpdate,
            @Valid MoreTypesDemo moreTypesDemo) {
        moreTypesDemo.copyTo(moreTypesDemoToUpdate);
        moreTypesDemoService.save(moreTypesDemoToUpdate);
        return moreTypesDemoToUpdate.copy();
    }

    @RequestMapping(value = "/{pk}", method = DELETE)
    @ResponseBody
    public boolean delete(@PathVariable("pk") MoreTypesDemo moreTypesDemo) {
        moreTypesDemoService.delete(moreTypesDemo);
        return true;
    }

    @RequestMapping("/autocomplete")
    @ResponseBody
    public List<AutoCompleteResult> autocomplete(@RequestParam(value = "term", required = false) String searchPattern,
            SearchParameters search) {
        if (searchPattern != null && !searchPattern.isEmpty()) {
            search.setSearchPattern(searchPattern);
        }
        List<AutoCompleteResult> ret = new ArrayList<AutoCompleteResult>();
        for (MoreTypesDemo moreTypesDemo : moreTypesDemoService.find(search.toSearchTemplate())) {
            String objectPk = moreTypesDemo.getPrimaryKey().toString();
            String objectLabel = formattingConversionService.convert(moreTypesDemo, String.class);
            ret.add(new AutoCompleteResult(objectPk, objectLabel));
        }
        return ret;
    }

    @ExceptionHandler()
    @ResponseStatus(value = INTERNAL_SERVER_ERROR)
    public void exception(Exception e, PrintWriter out) {
        out.write(e.getMessage());
    }
}