/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/formatter/Formatter.e.vm.java
 */
package com.dhenton9000.springfuse.formatter;

import java.text.ParseException;
import java.util.Locale;

import com.dhenton9000.springfuse.domain.Address;
import com.dhenton9000.springfuse.service.AddressService;
import com.dhenton9000.springfuse.formatter.support.DiscoverableFormatter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * {@link Formatter} for {@link Address} that is picked by automatically by {@link CustomFormattingConversionServiceFactory}
 * 
 * @see Formatter
 * @see CustomFormattingConversionServiceFactory
 */
@Component
public class AddressFormatter implements DiscoverableFormatter<Address> {

    @Autowired
    private AddressService addressService;

    @Override
    public Class<Address> getTarget() {
        return Address.class;
    }

    @Override
    public String print(Address address, Locale locale) {
        if (address == null) {
            return "";
        }

        StringBuilder sb = new StringBuilder();
        // make a nice display string here...

        if (address.getStreetName() != null) {
            sb.append(address.getStreetName()).append(" ");
        }

        if (address.getCity() != null) {
            sb.append(address.getCity()).append(" ");
        }

        if (sb.length() > 0) {
            return sb.toString();
        } else if (address.isPrimaryKeySet()) {
            return address.getPrimaryKey().toString();
        } else {
            return address.toString();
        }
    }

    @Override
    public Address parse(String text, Locale locale) throws ParseException {
        if (text == null || text.isEmpty()) {
            return new Address();
        }
        Address address = addressService.getByPrimaryKey(new Integer(text));
        return address != null ? address : new Address();
    }
}
