/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/manager/ModelGenerator.e.vm.java
 */
package com.dhenton9000.springfuse.service;

import java.util.*;

import com.dhenton9000.springfuse.util.*;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.dhenton9000.springfuse.domain.Document;

import com.dhenton9000.springfuse.domain.Account;
import com.dhenton9000.springfuse.service.AccountService;
import com.dhenton9000.springfuse.service.AccountGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Service
public class DocumentGenerator {

    /**
     * Returns a new Document instance filled with random values.
     */
    public Document getDocument() {
        Document document = new Document();

        // simple attributes follows
        document.setDocumentContentType("d");
        document.setDocumentSize(ValueGenerator.getNumeric(java.lang.Integer.class, "1"));
        document.setDocumentFileName("d");
        document.setDocumentBinary("d".getBytes());
        // mandatory relation
        Account account = accountGenerator.getAccount();
        accountService.save(account);
        document.setAccount(account);
        return document;
    }

    @Autowired
    private AccountService accountService;
    @Autowired
    private AccountGenerator accountGenerator;
}