package com.dhenton9000.hibernatesecurity;
// Generated Jun 17, 2010 4:41:51 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
 

/**
 * Applications generated by hbm2java
 */

public class Applications  implements java.io.Serializable, Cloneable {


     private int id;
     private String applicationName;
     private Set applicationGroupses = new HashSet(0);

    public Applications() {
        super();
    }

	
    public Applications(int id) {
        super();
        this.id = id;
    }
    public Applications(int id, String applicationName, Set applicationGroupses) {
       super();
       this.id = id;
       this.applicationName = applicationName;
       this.applicationGroupses = applicationGroupses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getApplicationName() {
        return this.applicationName;
    }
    
    public void setApplicationName(String applicationName) {
        this.applicationName = applicationName;
    }
    
    public Set getApplicationGroupses() {

        return this.applicationGroupses;
    }
     
    public void setApplicationGroupses(Set applicationGroupses) {
        this.applicationGroupses = applicationGroupses;
    }


  

    @Override
    public Applications clone() throws CloneNotSupportedException {

        Applications a = null;

        a = new Applications();
        a.setApplicationGroupses(getApplicationGroupses());
        a.setApplicationName(getApplicationName());
        a.setId(getId());

        return a;
    }
}


