/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/dao/DAO.e.vm.java
 */
package com.dhenton9000.springfuse.dao.more;

import com.dhenton9000.springfuse.dao.support.GenericDao;
import com.dhenton9000.springfuse.domain.more.MoreTypesDemo;

/**
 * DAO Interface for {@link MoreTypesDemo}
 */
public interface MoreTypesDemoDao extends GenericDao<MoreTypesDemo, Integer> {
}
