/**
 * Please modify this class to meet your needs
 * This class is not complete
 */
package com.dhenton9000.registration.components.ws;

import com.dhenton9000.registration.bindings.RegisterInput;
import com.dhenton9000.registration.bindings.RegisterResponse;
import java.math.BigDecimal;
import java.util.Calendar;
import org.apache.log4j.*;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-02-02T13:22:34.057-06:00
 * Generated source version: 2.5.1
 * 
 */
@javax.jws.WebService(serviceName = "RegistrationServiceWSDL",
portName = "RegistrationServiceWSDLSOAP",
targetNamespace = "uri:dhenton9000:registrationService",
wsdlLocation = "src/main/resources/RegistrationService.wsdl",
endpointInterface = "com.dhenton9000.registration.components.ws.RegistrationServiceWSDL")
public class RegistrationServiceWSDLImpl implements RegistrationServiceWSDL {

    private static final Logger logger = LogManager.getLogger(RegistrationServiceWSDLImpl.class.getName());

    /* (non-Javadoc)
     * @see com.dhenton9000.registration.components.ws.RegistrationServiceWSDL#register(com.dhenton9000.registration.components.ws.RegisterInput  inputParameter )*
     */
    @Override
    public RegisterResponse register(RegisterInput inputParameter) {
        logger.info("Executing operation register " + inputParameter.getName());


        String replyString = 
        "Thank you " + inputParameter.getName()+" for "+inputParameter.getRegistrationDetails().getPaymentPlan();
        logger.info("Web service is saying "+replyString);
        
        RegisterResponse _return = new RegisterResponse();
        _return.setResponseInformation(replyString);
        _return.setCurrentTime(Calendar.getInstance());
        BigDecimal dd = BigDecimal.valueOf(100.25d);
        _return.setTotalCost(dd);
        _return.setPaymentDepartment("Fred");
        return _return;

    }
}
