
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.dhenton9000.admissions.ws.impl;

import com.dhenton9000.admissions.components.ws.AdmitSubject;
import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-12-12T15:22:32.800-06:00
 * Generated source version: 2.5.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "AdmissionService",
                      portName = "AdmissionPort",
                      targetNamespace = "http://www.mule-health.com/SOA/service/admission/1.0",
                      wsdlLocation = "src/main/resources/AdmissionService.wsdl",
                      endpointInterface = "com.dhenton9000.admissions.ws.impl.Admission")
                      
public class AdmissionImpl implements Admission {

    private static final Logger LOG = Logger.getLogger(AdmissionImpl.class.getName());

    /* (non-Javadoc)
     * @see com.dhenton9000.admissions.components.ws.Admission#admitSubject(com.dhenton9000.admissions.components.ws.AdmitSubject  parameters )*
     */
    public com.dhenton9000.admissions.components.ws.AdmitSubjectResponse admitSubject(AdmitSubject parameters) { 
        LOG.info("Executing operation admitSubject");
        System.out.println(parameters);
        try {
            com.dhenton9000.admissions.components.ws.AdmitSubjectResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
