/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/web/controller/controller.e.vm.java
 */
package com.dhenton9000.springfuse.web.controller.more;

import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;

import com.dhenton9000.springfuse.domain.more.MoreTypesDemo;
import com.dhenton9000.springfuse.service.more.MoreTypesDemoService;

@Controller
@RequestMapping("/domain/moretypesdemo/")
public class MoreTypesDemoController {

    @Autowired
    private MoreTypesDemoService moreTypesDemoService;

    /**
     * Performs the list action.
     */
    @RequestMapping(value = { "list", "" })
    public String list(@ModelAttribute MoreTypesDemoSearchForm moreTypesDemoSearchForm, Model model) {
        model.addAttribute("moreTypesDemosCount", moreTypesDemoService.findCount(moreTypesDemoSearchForm
                .getMoreTypesDemo(), moreTypesDemoSearchForm.toSearchTemplate()));
        model.addAttribute("moreTypesDemos", moreTypesDemoService.find(moreTypesDemoSearchForm.getMoreTypesDemo(),
                moreTypesDemoSearchForm.toSearchTemplate()));
        return "domain/moretypesdemo/list";
    }

    /**
     * Serves the create form.
     */
    @RequestMapping(value = "create", method = GET)
    public String create(@ModelAttribute MoreTypesDemo moreTypesDemo) {
        return "domain/moretypesdemo/create";
    }

    /**
     * Performs the create action and redirect to the show view.
     */
    @RequestMapping(value = "create", method = { POST, PUT })
    public String create(@Valid @ModelAttribute MoreTypesDemo moreTypesDemo, BindingResult bindingResult) {
        if (bindingResult.hasErrors()) {
            return create(moreTypesDemo);
        }

        moreTypesDemoService.save(moreTypesDemo);
        return "redirect:/domain/moretypesdemo/show/" + moreTypesDemo.getPrimaryKey();
    }

    /**
     * Serves search by example form, search by pattern form and search by named query form.
     */
    @RequestMapping(value = "*", method = GET)
    public void catchAll(@ModelAttribute MoreTypesDemoSearchForm moreTypesDemoSearchForm) {
    }

}