/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/web/controller/restController.e.vm.java
 */
package com.dhenton9000.springfuse.web.controller;

import static org.springframework.http.HttpStatus.INTERNAL_SERVER_ERROR;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.support.FormattingConversionService;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

import com.dhenton9000.springfuse.web.util.AutoCompleteResult;
import com.dhenton9000.springfuse.web.util.SearchParameters;
import com.dhenton9000.springfuse.domain.Account;
import com.dhenton9000.springfuse.service.AccountService;

@Controller
@RequestMapping("domain/rest/account/")
public class AccountRestController {
    @Autowired
    public FormattingConversionService formattingConversionService;

    @Autowired
    private AccountService accountService;

    @RequestMapping(value = "/", method = POST)
    @ResponseBody
    public Account create(@Valid Account account) {
        accountService.save(account);
        return account.copy();
    }

    @RequestMapping(value = "/", method = POST, headers = "content-type:application/json")
    @ResponseBody
    public Account jsonCreate(@Valid @RequestBody Account account) {
        accountService.save(account);
        return account.copy();
    }

    @RequestMapping(value = "/", method = GET)
    @ResponseBody
    public List<Account> list(Account account, SearchParameters searchParameters) {
        List<Account> accounts = accountService.find(account, searchParameters.toSearchTemplate());
        List<Account> ret = new ArrayList<Account>();
        for (Account _account : accounts) {
            ret.add(_account.copy());
        }
        return ret;
    }

    @RequestMapping(value = "/{pk}", method = GET)
    @ResponseBody
    public Account get(@PathVariable("pk") Account account) {
        return account.copy();
    }

    @RequestMapping(value = "/{pk}", method = PUT)
    @ResponseBody
    public Account update(@PathVariable("pk") Account accountToUpdate, @Valid Account account) {
        account.copyTo(accountToUpdate);
        accountService.save(accountToUpdate);
        return accountToUpdate.copy();
    }

    @RequestMapping(value = "/{pk}", method = DELETE)
    @ResponseBody
    public boolean delete(@PathVariable("pk") Account account) {
        accountService.delete(account);
        return true;
    }

    @RequestMapping("/autocomplete")
    @ResponseBody
    public List<AutoCompleteResult> autocomplete(@RequestParam(value = "term", required = false) String searchPattern,
            SearchParameters search) {
        if (searchPattern != null && !searchPattern.isEmpty()) {
            search.setSearchPattern(searchPattern);
        }
        List<AutoCompleteResult> ret = new ArrayList<AutoCompleteResult>();
        for (Account account : accountService.find(search.toSearchTemplate())) {
            String objectPk = account.getPrimaryKey().toString();
            String objectLabel = formattingConversionService.convert(account, String.class);
            ret.add(new AutoCompleteResult(objectPk, objectLabel));
        }
        return ret;
    }

    @ExceptionHandler()
    @ResponseStatus(value = INTERNAL_SERVER_ERROR)
    public void exception(Exception e, PrintWriter out) {
        out.write(e.getMessage());
    }
}