/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/web/controller/controllerwithPathVariable.e.vm.java
 */
package com.dhenton9000.springfuse.web.controller;

import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

import com.dhenton9000.springfuse.domain.ContactInfo;
import com.dhenton9000.springfuse.service.ContactInfoService;
import com.dhenton9000.springfuse.domain.Account;
import com.dhenton9000.springfuse.service.AccountService;

@Controller
@RequestMapping("/domain/contactinfo/")
public class ContactInfoControllerWithPathVariable {
    @Autowired
    private ContactInfoService contactInfoService;
    @Autowired
    private AccountService accountService;

    /**
     * This method is invoked by Spring MVC before the handler methods.
     * <p>
     * The path variable is converted by SpringMVC to a ContactInfo via the {@link ContactInfoFormatter}.
     * Before being passed as an argument to the handler, SpringMVC binds the attributes on the resulting model,
     * then each handler method may receive the entity, potentially modified, as an argument.
     */
    @ModelAttribute
    public ContactInfo getContactInfo(@PathVariable("pk") ContactInfo contactInfo) {
        return contactInfo;
    }

    /**
     * Serves the show view for the entity.
     */
    @RequestMapping("show/{pk}")
    public String show(@ModelAttribute ContactInfo contactInfo) {
        return "domain/contactinfo/show";
    }

    /**
     * Serves the update form view.
     */
    @RequestMapping(value = "update/{pk}", method = GET)
    public String update(Model model) {
        bindListForSelectInputFields(model);
        return "domain/contactinfo/update";
    }

    /**
     * Performs the update action and redirect to the show view.
     */
    @RequestMapping(value = "update/{pk}", method = { PUT, POST })
    public String update(@Valid @ModelAttribute ContactInfo contactInfo, BindingResult bindingResult, Model model) {
        if (bindingResult.hasErrors()) {
            return update(model);
        }

        contactInfoService.save(contactInfo);
        return "redirect:/domain/contactinfo/show/" + contactInfo.getPrimaryKey();
    }

    /**
     * Serves the delete form asking the user if the entity should be really deleted.
     */
    @RequestMapping(value = "delete/{pk}", method = GET)
    public String delete() {
        return "domain/contactinfo/delete";
    }

    /**
     * Performs the delete action and redirect to the search view.
     */
    @RequestMapping(value = "delete/{pk}", method = { PUT, POST, DELETE })
    public String delete(@ModelAttribute ContactInfo contactInfo) {
        contactInfoService.delete(contactInfo);
        return "redirect:/domain/contactinfo/search";
    }

    /**
     * Binds to the passed model the possible values for select input fields.
     */
    private void bindListForSelectInputFields(Model model) {
        model.addAttribute("parents", accountService.find());
    }
}