/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/web/controller/controller.e.vm.java
 */
package com.dhenton9000.springfuse.web.controller;

import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;

import com.dhenton9000.springfuse.domain.Account;
import com.dhenton9000.springfuse.service.AccountService;
import com.dhenton9000.springfuse.domain.Role;
import com.dhenton9000.springfuse.service.RoleService;

@Controller
@RequestMapping("/domain/account/")
public class AccountController {

    @Autowired
    private AccountService accountService;
    @Autowired
    private RoleService roleService;

    /**
     * Performs the list action.
     */
    @RequestMapping(value = { "list", "" })
    public String list(@ModelAttribute AccountSearchForm accountSearchForm, Model model) {
        model.addAttribute("accountsCount", accountService.findCount(accountSearchForm.getAccount(), accountSearchForm
                .toSearchTemplate()));
        model.addAttribute("accounts", accountService.find(accountSearchForm.getAccount(), accountSearchForm
                .toSearchTemplate()));
        return "domain/account/list";
    }

    /**
     * Serves the create form.
     */
    @RequestMapping(value = "create", method = GET)
    public String create(@ModelAttribute Account account, Model model) {
        bindListForSelectInputFields(model);
        return "domain/account/create";
    }

    /**
     * Performs the create action and redirect to the show view.
     */
    @RequestMapping(value = "create", method = { POST, PUT })
    public String create(@Valid @ModelAttribute Account account, BindingResult bindingResult, Model model) {
        if (bindingResult.hasErrors()) {
            return create(account, model);
        }

        if (account.getContactInformation() != null) {
            // use the other side
            account.getContactInformation().setParent(account);
        }

        accountService.save(account);
        return "redirect:/domain/account/show/" + account.getPrimaryKey();
    }

    /**
     * Serves search by example form, search by pattern form and search by named query form.
     */
    @RequestMapping(value = "*", method = GET)
    public void catchAll(@ModelAttribute AccountSearchForm accountSearchForm, Model model) {
        bindListForSelectInputFields(model);
    }

    /**
     * Binds to the passed model the possible values for select input fields.
     */
    private void bindListForSelectInputFields(Model model) {
        model.addAttribute("roles", roleService.find());
    }
}