/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/web/controller/restController.e.vm.java
 */
package com.dhenton9000.springfuse.web.controller;

import static org.springframework.http.HttpStatus.INTERNAL_SERVER_ERROR;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.support.FormattingConversionService;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

import com.dhenton9000.springfuse.web.util.AutoCompleteResult;
import com.dhenton9000.springfuse.web.util.SearchParameters;
import com.dhenton9000.springfuse.domain.Book;
import com.dhenton9000.springfuse.service.BookService;

@Controller
@RequestMapping("domain/rest/book/")
public class BookRestController {
    @Autowired
    public FormattingConversionService formattingConversionService;

    @Autowired
    private BookService bookService;

    @RequestMapping(value = "/", method = POST)
    @ResponseBody
    public Book create(@Valid Book book) {
        bookService.save(book);
        return book.copy();
    }

    @RequestMapping(value = "/", method = POST, headers = "content-type:application/json")
    @ResponseBody
    public Book jsonCreate(@Valid @RequestBody Book book) {
        bookService.save(book);
        return book.copy();
    }

    @RequestMapping(value = "/", method = GET)
    @ResponseBody
    public List<Book> list(Book book, SearchParameters searchParameters) {
        List<Book> books = bookService.find(book, searchParameters.toSearchTemplate());
        List<Book> ret = new ArrayList<Book>();
        for (Book _book : books) {
            ret.add(_book.copy());
        }
        return ret;
    }

    @RequestMapping(value = "/{pk}", method = GET)
    @ResponseBody
    public Book get(@PathVariable("pk") Book book) {
        return book.copy();
    }

    @RequestMapping(value = "/{pk}", method = PUT)
    @ResponseBody
    public Book update(@PathVariable("pk") Book bookToUpdate, @Valid Book book) {
        book.copyTo(bookToUpdate);
        bookService.save(bookToUpdate);
        return bookToUpdate.copy();
    }

    @RequestMapping(value = "/{pk}", method = DELETE)
    @ResponseBody
    public boolean delete(@PathVariable("pk") Book book) {
        bookService.delete(book);
        return true;
    }

    @RequestMapping("/autocomplete")
    @ResponseBody
    public List<AutoCompleteResult> autocomplete(@RequestParam(value = "term", required = false) String searchPattern,
            SearchParameters search) {
        if (searchPattern != null && !searchPattern.isEmpty()) {
            search.setSearchPattern(searchPattern);
        }
        List<AutoCompleteResult> ret = new ArrayList<AutoCompleteResult>();
        for (Book book : bookService.find(search.toSearchTemplate())) {
            String objectPk = book.getPrimaryKey().toString();
            String objectLabel = formattingConversionService.convert(book, String.class);
            ret.add(new AutoCompleteResult(objectPk, objectLabel));
        }
        return ret;
    }

    @ExceptionHandler()
    @ResponseStatus(value = INTERNAL_SERVER_ERROR)
    public void exception(Exception e, PrintWriter out) {
        out.write(e.getMessage());
    }
}