/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/web/controller/controller.e.vm.java
 */
package com.dhenton9000.springfuse.web.controller;

import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;

import com.dhenton9000.springfuse.domain.ContactInfo;
import com.dhenton9000.springfuse.service.ContactInfoService;
import com.dhenton9000.springfuse.domain.Account;
import com.dhenton9000.springfuse.service.AccountService;

@Controller
@RequestMapping("/domain/contactinfo/")
public class ContactInfoController {

    @Autowired
    private ContactInfoService contactInfoService;
    @Autowired
    private AccountService accountService;

    /**
     * Performs the list action.
     */
    @RequestMapping(value = { "list", "" })
    public String list(@ModelAttribute ContactInfoSearchForm contactInfoSearchForm, Model model) {
        model.addAttribute("contactInfosCount", contactInfoService.findCount(contactInfoSearchForm.getContactInfo(),
                contactInfoSearchForm.toSearchTemplate()));
        model.addAttribute("contactInfos", contactInfoService.find(contactInfoSearchForm.getContactInfo(),
                contactInfoSearchForm.toSearchTemplate()));
        return "domain/contactinfo/list";
    }

    /**
     * Serves the create form.
     */
    @RequestMapping(value = "create", method = GET)
    public String create(@ModelAttribute ContactInfo contactInfo, Model model) {
        bindListForSelectInputFields(model);
        return "domain/contactinfo/create";
    }

    /**
     * Performs the create action and redirect to the show view.
     */
    @RequestMapping(value = "create", method = { POST, PUT })
    public String create(@Valid @ModelAttribute ContactInfo contactInfo, BindingResult bindingResult, Model model) {
        if (bindingResult.hasErrors()) {
            return create(contactInfo, model);
        }

        if (contactInfo.getParent() != null) {
            // use the other side
            contactInfo.getParent().setContactInformation(contactInfo);
        }

        contactInfoService.save(contactInfo);
        return "redirect:/domain/contactinfo/show/" + contactInfo.getPrimaryKey();
    }

    /**
     * Serves search by example form, search by pattern form and search by named query form.
     */
    @RequestMapping(value = "*", method = GET)
    public void catchAll(@ModelAttribute ContactInfoSearchForm contactInfoSearchForm, Model model) {
        bindListForSelectInputFields(model);
    }

    /**
     * Binds to the passed model the possible values for select input fields.
     */
    private void bindListForSelectInputFields(Model model) {
        model.addAttribute("parents", accountService.find());
    }
}