/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/web/controller/restController.e.vm.java
 */
package com.dhenton9000.springfuse.web.controller;

import static org.springframework.http.HttpStatus.INTERNAL_SERVER_ERROR;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.support.FormattingConversionService;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

import com.dhenton9000.springfuse.web.util.AutoCompleteResult;
import com.dhenton9000.springfuse.web.util.SearchParameters;
import com.dhenton9000.springfuse.domain.Document;
import com.dhenton9000.springfuse.service.DocumentService;

@Controller
@RequestMapping("domain/rest/document/")
public class DocumentRestController {
    @Autowired
    public FormattingConversionService formattingConversionService;

    @Autowired
    private DocumentService documentService;

    @RequestMapping(value = "/", method = POST)
    @ResponseBody
    public Document create(@Valid Document document) {
        documentService.save(document);
        return document.copy();
    }

    @RequestMapping(value = "/", method = POST, headers = "content-type:application/json")
    @ResponseBody
    public Document jsonCreate(@Valid @RequestBody Document document) {
        documentService.save(document);
        return document.copy();
    }

    @RequestMapping(value = "/", method = GET)
    @ResponseBody
    public List<Document> list(Document document, SearchParameters searchParameters) {
        List<Document> documents = documentService.find(document, searchParameters.toSearchTemplate());
        List<Document> ret = new ArrayList<Document>();
        for (Document _document : documents) {
            ret.add(_document.copy());
        }
        return ret;
    }

    @RequestMapping(value = "/{pk}", method = GET)
    @ResponseBody
    public Document get(@PathVariable("pk") Document document) {
        return document.copy();
    }

    @RequestMapping(value = "/{pk}", method = PUT)
    @ResponseBody
    public Document update(@PathVariable("pk") Document documentToUpdate, @Valid Document document) {
        document.copyTo(documentToUpdate);
        documentService.save(documentToUpdate);
        return documentToUpdate.copy();
    }

    @RequestMapping(value = "/{pk}", method = DELETE)
    @ResponseBody
    public boolean delete(@PathVariable("pk") Document document) {
        documentService.delete(document);
        return true;
    }

    @RequestMapping("/autocomplete")
    @ResponseBody
    public List<AutoCompleteResult> autocomplete(@RequestParam(value = "term", required = false) String searchPattern,
            SearchParameters search) {
        if (searchPattern != null && !searchPattern.isEmpty()) {
            search.setSearchPattern(searchPattern);
        }
        List<AutoCompleteResult> ret = new ArrayList<AutoCompleteResult>();
        for (Document document : documentService.find(search.toSearchTemplate())) {
            String objectPk = document.getPrimaryKey().toString();
            String objectLabel = formattingConversionService.convert(document, String.class);
            ret.add(new AutoCompleteResult(objectPk, objectLabel));
        }
        return ret;
    }

    @ExceptionHandler()
    @ResponseStatus(value = INTERNAL_SERVER_ERROR)
    public void exception(Exception e, PrintWriter out) {
        out.write(e.getMessage());
    }
}