/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/formatter/Formatter.e.vm.java
 */
package com.dhenton9000.springfuse.formatter;

import java.text.ParseException;
import java.util.Locale;

import com.dhenton9000.springfuse.domain.ContactInfo;
import com.dhenton9000.springfuse.service.ContactInfoService;
import com.dhenton9000.springfuse.formatter.support.DiscoverableFormatter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * {@link Formatter} for {@link ContactInfo} that is picked by automatically by {@link CustomFormattingConversionServiceFactory}
 * 
 * @see Formatter
 * @see CustomFormattingConversionServiceFactory
 */
@Component
public class ContactInfoFormatter implements DiscoverableFormatter<ContactInfo> {

    @Autowired
    private ContactInfoService contactInfoService;

    @Override
    public Class<ContactInfo> getTarget() {
        return ContactInfo.class;
    }

    @Override
    public String print(ContactInfo contactInfo, Locale locale) {
        if (contactInfo == null) {
            return "";
        }

        StringBuilder sb = new StringBuilder();
        // make a nice display string here...

        if (contactInfo.getCivility() != null) {
            sb.append(contactInfo.getCivility()).append(" ");
        }

        if (contactInfo.getLastName() != null) {
            sb.append(contactInfo.getLastName()).append(" ");
        }

        if (contactInfo.getFirstName() != null) {
            sb.append(contactInfo.getFirstName()).append(" ");
        }

        if (sb.length() > 0) {
            return sb.toString();
        } else if (contactInfo.isPrimaryKeySet()) {
            return contactInfo.getPrimaryKey().toString();
        } else {
            return contactInfo.toString();
        }
    }

    @Override
    public ContactInfo parse(String text, Locale locale) throws ParseException {
        if (text == null || text.isEmpty()) {
            return new ContactInfo();
        }
        ContactInfo contactInfo = contactInfoService.getByPrimaryKey(new Integer(text));
        return contactInfo != null ? contactInfo : new ContactInfo();
    }
}
