/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/formatter/Formatter.e.vm.java
 */
package com.dhenton9000.springfuse.formatter;

import java.text.ParseException;
import java.util.Locale;

import com.dhenton9000.springfuse.domain.Document;
import com.dhenton9000.springfuse.service.DocumentService;
import com.dhenton9000.springfuse.formatter.support.DiscoverableFormatter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * {@link Formatter} for {@link Document} that is picked by automatically by {@link CustomFormattingConversionServiceFactory}
 * 
 * @see Formatter
 * @see CustomFormattingConversionServiceFactory
 */
@Component
public class DocumentFormatter implements DiscoverableFormatter<Document> {

    @Autowired
    private DocumentService documentService;

    @Override
    public Class<Document> getTarget() {
        return Document.class;
    }

    @Override
    public String print(Document document, Locale locale) {
        if (document == null) {
            return "";
        }

        StringBuilder sb = new StringBuilder();
        // make a nice display string here...

        if (document.getDocumentContentType() != null) {
            sb.append(document.getDocumentContentType()).append(" ");
        }

        if (document.getDocumentFileName() != null) {
            sb.append(document.getDocumentFileName()).append(" ");
        }

        if (sb.length() > 0) {
            return sb.toString();
        } else if (document.isPrimaryKeySet()) {
            return document.getPrimaryKey();
        } else {
            return document.toString();
        }
    }

    @Override
    public Document parse(String text, Locale locale) throws ParseException {
        if (text == null || text.isEmpty()) {
            return new Document();
        }
        Document document = documentService.getByPrimaryKey(text);
        return document != null ? document : new Document();
    }
}
