/**
 * Please modify this class to meet your needs This class is not complete
 */
package com.dhenton9000.registration.components.ws;

import com.dhenton9000.registration.bindings.RegisterInput;
import com.dhenton9000.registration.bindings.RegisterResponse;
import java.math.BigDecimal;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.jms.JMSException;
import javax.jms.Message;
import javax.jms.Session;
import org.apache.log4j.LogManager;
import org.mule.api.MuleContext;
import org.mule.api.context.MuleContextAware;
import org.mule.api.transformer.Transformer;
import org.mule.api.transformer.TransformerException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jms.core.JmsTemplate;
import org.springframework.jms.core.MessageCreator;
import org.springframework.stereotype.Service;
import org.mule.module.xml.transformer.jaxb.JAXBMarshallerTransformer;

/**
 * This class was generated by Apache CXF 2.6.1 2012-07-17T12:29:43.228-05:00
 * Generated source version: 2.6.1
 *
 */
@javax.jws.WebService(serviceName = "RegistrationServiceWSDL",
portName = "RegistrationServiceWSDLSOAP",
targetNamespace = "uri:dhenton9000:registrationService",
wsdlLocation = "src/main/resources/RegistrationService.wsdl",
endpointInterface = "com.dhenton9000.registration.components.ws.RegistrationServiceWSDL")
public class RegistrationServiceWSDLImpl implements RegistrationServiceWSDL, MuleContextAware {
    public static final String JAXB_TO_STRING_BEAN_NAME = "jaxbToString";
    public static final String JMS_ACTIVE_MQ_TEMPLATE_BEAN_NAME = "jmsActiveMQTemplate";

    private static final org.apache.log4j.Logger logger = LogManager.getLogger(RegistrationServiceWSDLImpl.class.getName());
    private MuleContext muleContext = null;
    private JmsTemplate jmsTemplate = null;
    /*
     * (non-Javadoc) @see
     * com.dhenton9000.registration.components.ws.RegistrationServiceWSDL#register(com.dhenton9000.registration.components.ws.RegisterInput
     * inputParameter )*
     */

    @Override
    public RegisterResponse register(final RegisterInput inputParameter) {
        logger.info("Executing operation register " + inputParameter.getName());
        String replyString =
                "Thank you " + inputParameter.getName() + " for " + inputParameter.getRegistrationDetails().getPaymentPlan();
        logger.info("Web service is saying " + replyString);

        JAXBMarshallerTransformer tr = (JAXBMarshallerTransformer) getMuleContext().getRegistry().get(JAXB_TO_STRING_BEAN_NAME);
        String inputParameterString = null;
        try {
            inputParameterString = (String) tr.transform(inputParameter);

        } catch (TransformerException ex) {
            logger.error("transformer problem " + ex.getMessage());
        }

        final String outM = inputParameterString;
        jmsTemplate.send(new MessageCreator() {

            @Override
            public Message createMessage(Session sn) throws JMSException {
                return sn.createTextMessage(outM);
            }
        });


        RegisterResponse _return = new RegisterResponse();
        _return.setResponseInformation(replyString);
        _return.setCurrentTime(Calendar.getInstance());
        BigDecimal dd = BigDecimal.valueOf(100.25d);
        _return.setTotalCost(dd);
        _return.setPaymentDepartment("This is a response");
        logger.info("about to return "+_return);
        return _return;

    }

    /**
     * @return the jmsTemplate
     */
    public JmsTemplate getJmsTemplate() {
        return jmsTemplate;
    }

    @Override
    public void setMuleContext(MuleContext mc) {
        jmsTemplate = (JmsTemplate) mc.getRegistry().get(JMS_ACTIVE_MQ_TEMPLATE_BEAN_NAME);
        muleContext = mc;
    }

    /**
     * @return the muleContext
     */
    public MuleContext getMuleContext() {
        return muleContext;
    }
}
