package com.dhenton9000.registration.components.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Map;
import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-17T12:29:43.313-05:00
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "RegistrationServiceWSDL", 
                  wsdlLocation = "src/main/resources/RegistrationService.wsdl",
                  targetNamespace = "uri:dhenton9000:registrationService") 
public class RegistrationServiceWSDLClient extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("uri:dhenton9000:registrationService", "RegistrationServiceWSDL");
    public final static QName RegistrationServiceWSDLSOAP = new QName("uri:dhenton9000:registrationService", "RegistrationServiceWSDLSOAP");
    static {
        URL url = RegistrationServiceWSDLClient.class.getResource("src/main/resources/RegistrationService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(RegistrationServiceWSDLClient.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "src/main/resources/RegistrationService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public RegistrationServiceWSDLClient(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RegistrationServiceWSDLClient(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistrationServiceWSDLClient() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns RegistrationServiceWSDL
     */
    @WebEndpoint(name = "RegistrationServiceWSDLSOAP")
    public RegistrationServiceWSDL getRegistrationServiceWSDLSOAP() {
        return super.getPort(RegistrationServiceWSDLSOAP, RegistrationServiceWSDL.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistrationServiceWSDL
     */
    @WebEndpoint(name = "RegistrationServiceWSDLSOAP")
    public RegistrationServiceWSDL getRegistrationServiceWSDLSOAP(WebServiceFeature... features) {
        return super.getPort(RegistrationServiceWSDLSOAP, RegistrationServiceWSDL.class, features);
    }
    
    
     /**
     * create a client 
     * @param wsdlClasspathLocation RegistrationService.wsdl
     * @param somepathToSomeService registration
     * @param port 9091
     * @return the configured client http://localhost:9091/registration
     * see wiki entry on mule for more parameters
     */
    public static RegistrationServiceWSDL createPort(String wsdlClasspathLocation,
            String somepathToSomeService, String port) {

        ClassLoader cl = Thread.currentThread().getContextClassLoader();
        URL wsdlURL = cl.getResource(wsdlClasspathLocation);

        RegistrationServiceWSDL svc =
                (new RegistrationServiceWSDLClient(wsdlURL)).getRegistrationServiceWSDLSOAP();
        BindingProvider bindingPort = (BindingProvider) svc;
        Map<String, Object> requestContext =
                bindingPort.getRequestContext();
        requestContext.put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY,
                "http://localhost:" + port + "/"+somepathToSomeService);

        return svc;
    }
    
    
    public static RegistrationServiceWSDL createPort()
    {
        return createPort("RegistrationService.wsdl","registration","9091");
    }
    
    

}
