/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/web/controller/controller.e.vm.java
 */
package com.dhenton9000.springfuse.web.controller;

import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;

import com.dhenton9000.springfuse.domain.Book;
import com.dhenton9000.springfuse.service.BookService;

@Controller
@RequestMapping("/domain/book/")
public class BookController {

    @Autowired
    private BookService bookService;

    /**
     * Performs the list action.
     */
    @RequestMapping(value = { "list", "" })
    public String list(@ModelAttribute BookSearchForm bookSearchForm, Model model) {
        model.addAttribute("booksCount", bookService.findCount(bookSearchForm.getBook(), bookSearchForm
                .toSearchTemplate()));
        model.addAttribute("books", bookService.find(bookSearchForm.getBook(), bookSearchForm.toSearchTemplate()));
        return "domain/book/list";
    }

    /**
     * Serves the create form.
     */
    @RequestMapping(value = "create", method = GET)
    public String create(@ModelAttribute Book book) {
        return "domain/book/create";
    }

    /**
     * Performs the create action and redirect to the show view.
     */
    @RequestMapping(value = "create", method = { POST, PUT })
    public String create(@Valid @ModelAttribute Book book, BindingResult bindingResult) {
        if (bindingResult.hasErrors()) {
            return create(book);
        }

        if (book.getAccount() != null) {
            // use the other side
            book.getAccount().addBook(book);
        }

        bookService.save(book);
        return "redirect:/domain/book/show/" + book.getPrimaryKey();
    }

    /**
     * Serves search by example form, search by pattern form and search by named query form.
     */
    @RequestMapping(value = "*", method = GET)
    public void catchAll(@ModelAttribute BookSearchForm bookSearchForm) {
    }

}