/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/web/controller/SearchForm.e.vm.java
 */
package com.dhenton9000.springfuse.web.controller;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import com.dhenton9000.springfuse.dao.support.DateRange;
import com.dhenton9000.springfuse.web.util.DateRangeUtil;
import com.dhenton9000.springfuse.domain.ContactInfo;
import com.dhenton9000.springfuse.web.util.SearchForm;
import com.dhenton9000.springfuse.web.util.NullRestriction;

public class ContactInfoSearchForm extends SearchForm implements Serializable {
    private static final long serialVersionUID = 1L;
    private ContactInfo contactInfo = new ContactInfo();

    /**
     * The ContactInfo instance used as an example.
     */
    public ContactInfo getContactInfo() {
        return contactInfo;
    }

    //------------------------
    // support for date ranges
    //------------------------    
    private DateRangeUtil birthDateRange = new DateRangeUtil("birthDate");
    private DateRangeUtil otherDateRange = new DateRangeUtil("otherDate");

    /**
     * The {@link DateRangeUtil} for the birthDate attribute.
     */
    public DateRangeUtil getBirthDateRange() {
        return birthDateRange;
    }

    /**
     * The {@link DateRangeUtil} for the otherDate attribute.
     */
    public DateRangeUtil getOtherDateRange() {
        return otherDateRange;
    }

    @Override
    protected List<DateRange> getDateRanges() {
        List<DateRange> result = new ArrayList<DateRange>();
        result.add(getBirthDateRange());
        result.add(getOtherDateRange());
        return result;
    }

    private NullRestriction parentNullRestriction = new NullRestriction("parent");

    public NullRestriction getParentNullRestriction() {
        return parentNullRestriction;
    }

    @Override
    public List<NullRestriction> getNullRestrictions() {
        List<NullRestriction> result = new ArrayList<NullRestriction>();
        result.add(parentNullRestriction);
        return result;
    }
}