/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/web/controller/controller.e.vm.java
 */
package com.dhenton9000.springfuse.web.controller;

import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;

import com.dhenton9000.springfuse.domain.Legacy;
import com.dhenton9000.springfuse.service.LegacyService;

@Controller
@RequestMapping("/domain/legacy/")
public class LegacyController {

    @Autowired
    private LegacyService legacyService;

    /**
     * Performs the list action.
     */
    @RequestMapping(value = { "list", "" })
    public String list(@ModelAttribute LegacySearchForm legacySearchForm, Model model) {
        model.addAttribute("legaciesCount", legacyService.findCount(legacySearchForm.getLegacy(), legacySearchForm
                .toSearchTemplate()));
        model.addAttribute("legacies", legacyService.find(legacySearchForm.getLegacy(), legacySearchForm
                .toSearchTemplate()));
        return "domain/legacy/list";
    }

    /**
     * Serves the create form.
     */
    @RequestMapping(value = "create", method = GET)
    public String create(@ModelAttribute Legacy legacy) {
        return "domain/legacy/create";
    }

    /**
     * Performs the create action and redirect to the show view.
     */
    @RequestMapping(value = "create", method = { POST, PUT })
    public String create(@Valid @ModelAttribute Legacy legacy, BindingResult bindingResult) {
        if (bindingResult.hasErrors()) {
            return create(legacy);
        }

        legacyService.save(legacy);
        return "redirect:/domain/legacy/show/" + legacy.getPrimaryKey();
    }

    /**
     * Serves search by example form, search by pattern form and search by named query form.
     */
    @RequestMapping(value = "*", method = GET)
    public void catchAll(@ModelAttribute LegacySearchForm legacySearchForm) {
    }

}