/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/web/controller/SearchForm.e.vm.java
 */
package com.dhenton9000.springfuse.web.controller;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import com.dhenton9000.springfuse.domain.Role;
import com.dhenton9000.springfuse.web.util.SearchForm;
import com.dhenton9000.springfuse.web.util.NullRestriction;

public class RoleSearchForm extends SearchForm implements Serializable {
    private static final long serialVersionUID = 1L;
    private Role role = new Role();

    /**
     * The Role instance used as an example.
     */
    public Role getRole() {
        return role;
    }

    @Override
    public List<NullRestriction> getNullRestrictions() {
        List<NullRestriction> result = new ArrayList<NullRestriction>();
        return result;
    }
}